name: "Modify and Pack Unsigned IPA"

on:
  workflow_dispatch:

jobs:
  package-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Zip Payload into Unsigned IPA
        run: |
          mkdir -p build
          zip -r build/SOULBLAZERS_Unsigned.ipa Payload/

      - name: Upload Finished IPA
        uses: actions/upload-artifact@v4
        with:
          name: soulblazers-unsigned-ipa
          path: build/SOULBLAZERS_Unsigned.ipa